name: Build and Deploy Site
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN: stable
      ROOT_PATH: .
      OUT_DIRECTORY: dist/public
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus-CLI
        run: cargo binstall dioxus-cli --no-confirm --force

      - name: Build Project
        run: |
          cd ${{ env.ROOT_PATH }}
          dx bundle --platform web --release --out-dir "dist"
        shell: bash

      - name: Install Vercel Cli
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
