name: Build and Deploy Dioxus Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN: stable
      ROOT_PATH: .
      OUT_DIRECTORY: target/dx/bajrangcoder/release/web/public

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli
        shell: bash

      - name: Build Project
        run: |
          cd ${{ env.ROOT_PATH }}
          dx bundle --platform web
          cp ./${{ env.OUT_DIRECTORY }}/index.html ./${{ env.OUT_DIRECTORY }}/404.html
        shell: bash

      - name: Deploy Project
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ${{ env.OUT_DIRECTORY }}
          clean: false
