name: Build and Deploy Dioxus Static Site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TOOLCHAIN: stable
      ROOT_PATH: .
      OUT_DIRECTORY: target/dx/bajrangcoder/release/web/public
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Cargo Binstall
        uses: cargo-bins/cargo-binstall@main
      
      - name: Install Dioxus-CLI
        run: cargo binstall dioxus-cli --no-confirm --force
      
      - name: Build Project
        run: |
          cd ${{ env.ROOT_PATH }}
          dx bundle --platform web --release
          cp ./${{ env.OUT_DIRECTORY }}/index.html ./${{ env.OUT_DIRECTORY }}/404.html
        shell: bash
      
      - name: List built files (for debugging)
        run: |
          ls -la ${{ env.OUT_DIRECTORY }}
        shell: bash
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ${{ env.OUT_DIRECTORY }}
          clean: true  # Set to false if you want to preserve existing files
